# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Vehicle_Indexer
networks:
- id: 80084
  start_block: 0
  contracts:
  - name: VehicleManagement
    address:
    - 0xCd951A3b471cde1a3dD6E8b84A5B54E89E30f47D
    handler: src/EventHandlers.ts
    events:
    - event: VehicleRegistered(uint256 indexed vehicleId, address owner, bytes32 model)
rollback_on_reorg: false
