# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: vehicle_indexer
networks:
- id: 80002
  start_block: 0
  contracts:
  - name: VehicleManagement
    address:
    - 0x77cbfeA07320f53110C3144e1e75Fd610A37F01a
    handler: src/EventHandlers.ts
    events:
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: VehicleRegistered(uint256 indexed vehicleId, address owner, bytes32 model)
rollback_on_reorg: false
